
export type ERItem = {
    icon: string
    name: string
    weapon_type: WeaponType
    scaling: Stat[]
    ash_of_war: AshOfWar
    guard_boost: number
    damage: DamageType[]
    weight: number
    optain: WayToOptain[]
    location: Location[]
}

export type RatedERItem = ERItem & {
    c_scaling: ParticalCorrectList,
    c_damage: ParticalCorrectList,
    c_optain: ParticalCorrectList,
    c_location: ParticalCorrectList,
}

export type ParticalCorrectList = 'y' | 'n' | 'p'

enum WayToOptain {
    Remembrance = 'Remembrance',
    Bossdrop = 'Boss Reward',
    FindInWorld = 'Find in World',
    Buy = 'Buy',
    GuaranteedDrop = 'Guaranteed Drop',
    RandomDrop = 'Random Drop',
    StartingEquipment = 'Starting Equipment',
    StoneswordKey = 'Stonesword Key',
    QuestReward = 'Quest Reward',
}

enum WeaponType {
    Dagger = 'Dagger',
    StraightSword = 'Straight Sword',
    Greatsword = 'Greatsword',
    ColossalSword = 'Colossal Sword',
    ThrustingSword = 'Thrusting Sword',
    HeavyThrustingSword = 'Heavy Thrusting Sword',
    CurvedSword = 'Curved Sword',
    CurvedGreatsword = 'Curved Greatsword',
    Katana = 'Katana',
    Twinblade = 'Twinblade',
    Axe = 'Axe',
    Greataxe = 'Greataxe',
    Hammer = 'Hammer',
    Flail = 'Flail',
    GreatHammer = 'Great Hammer',
    ColossalWeapon = 'Colossal Weapon',
    Spear = 'Spear',
    GreatSpear = 'Great Spear',
    Halberd = 'Halberd',
    Reaper = 'Reaper',
    Whip = 'Whip',
    Fist = 'Fist',
    Claw = 'Claw',
    LightBow = 'Light Bow',
    Bow = 'Bow',
    Greatbow = 'Greatbow',
    Crossbow = 'Crossbow',
    Ballista = 'Ballista',
    GlintstoneStaff = 'Glintstone Staff',
    SacredSeal = 'Sacred Seal',
    Torch = 'Torch',
    ThrustingShield = 'Thrusting Shield',
    HandToHandArt = 'Hand-to-Hand Art',
    ThrowingBlade = 'Throwing Blade',
    BackhandBlade = 'Backhand Blade',
    PerfumeBottle = 'Perfume Bottle',
    BeastClaw = 'Beast Claw',
    LightGreatsword = 'Light Greatsword',
    GreatKatana = 'Great Katana',
    SmallShield = 'Small Shield',
    MediumShield = 'Medium Shield',
    Greatshield = 'Greatshield',
}

enum Location {
    AinselRiver = 'Ainsel River',
    DeeprootDepths = 'Deeproot Depths',
    SiofraRiver = 'Siofra River',

    Limgrave = 'Limgrave',
    WeepingPeninsula = 'Weeping Peninsula',
    LiurniaOfTheLakes = 'Liurnia of the Lakes',
    Caelid = 'Caelid',
    Dragonbarrow = 'Dragonbarrow',
    AltusPlateau = 'Altus Plateau',
    MtGelmir = 'Mt. Gelmir',
    CapitalOutskirts = 'Capital Outskirts',
    Leyndell = 'Leyndell',
    MountaintopsOfTheGiants = 'Mountaintops of the Giants',
    CrumblingFaramAzula = 'Crumbling Faram Azula',
    ForbiddenLands = 'Forbidden Lands',
    ConsectratedSnowfield = 'Consectrated Snowfield',
    MiquellasHailigtree = 'Miquella\'s Hailigtree',

    GravesitePlain = 'Gravesite Plain',
    ScaduAltus = 'Scadu Altus',
    RauhBase = 'Rauh Base',
    AncientRuinsOfRauh = 'Ancient Ruins of Rauh',
    CeruleanCoast = 'Cerulean Coast',
    CharosHiddenGrave = 'Charo\'s Hidden Grave',
    JaggedPeak = 'Jagged Peak',
    AbyssalWoods = 'Abyssal Woods',
    FingerRuinsOfRhia = 'Finger Ruins of Rhia',
    ScaduView = 'Scadu View',
    EnirIlim = 'Enir Ilim',
    Hinterlands = 'Hinterlands',

    RoundtableHold = 'Roundtable Hold',
}

enum Stat {
    Str = 'Str',
    Dex = 'Dex',
    Int = 'Int',
    Fai = 'Fai',
    Arc = 'Arc',
}

enum AshOfWar {
    Standard = 'Standard',
    Heavy = 'Heavy',
    Keen = 'Keen',
    Quality = 'Quality',
    Fire = 'Fire',
    FlameArt = 'Flame Art',
    Lightning = 'Lightning',
    Sacred = 'Sacred',
    Magic = 'Magic',
    Cold = 'Cold',
    Poison = 'Poison',
    Blood = 'Blood',
    Occult = 'Occult',

    Unique = 'Unique',
    NoSkill = 'No Skill',
}

enum DamageType {
    Standard = 'Standard',
    Strike = 'Strike',
    Slash = 'Slash',
    Pierce = 'Pierce',
}

export const AllEldenRingItems: ERItem[] = [
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/great_katana_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragon-hunters_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Dragon-Hunter's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 37,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 10.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rakshasas_great_katana_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Rakshasa's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/milady_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Milady",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 36,
        damage: [DamageType.Standard, DamageType.Pierce],
        weight: 6.5,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ledas_sword_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Leda's Sword",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 35,
        weight: 7.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Bossdrop],
        location: [Location.EnirIlim],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rellanas_twinblade_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Rellana's Twin Blades",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 35,
        weight: 8,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Remembrance],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/red_bears_claw_beast_claws_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Red Bear's Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 22,
        weight: 4,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/beast_claw_beast_claws_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Beast Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 3,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/firespark_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Firespark Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/chilling_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Chilling Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Int],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CharosHiddenGrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/frenzyflame_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Frenzyflame Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.AbyssalWoods],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/lightning_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Lightning Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CeruleanCoast],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/deadly_poison_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Deadly Poison Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Arc],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard],
        optain: [WayToOptain.Buy],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/backhand_blade_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Backhand Blade",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 15,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/smithscript_cirque_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Smithscript Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 25,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/curseblades_cirque_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Curseblade's Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 45,
        weight: 4.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.RandomDrop],
        location: [Location.GravesitePlain, Location.EnirIlim, Location.ScaduAltus, Location.AbyssalWoods, Location.CharosHiddenGrave, Location.CeruleanCoast, Location.AncientRuinsOfRauh],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/smithscript_dagger_throwing_blade_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Smithscript Dagger",
        weapon_type: WeaponType.ThrowingBlade,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dryleaf_arts_hand-to-hand_arts_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Dryleaf Arts",
        weapon_type: WeaponType.HandToHandArt,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 1,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/danes_footwork_hand-to-hand_arts_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Dane's Footwork",
        weapon_type: WeaponType.HandToHandArt,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 1,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.EnirIlim],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dueling_shield_thrusting_shields_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Dueling Shield",
        weapon_type: WeaponType.ThrustingShield,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 50,
        weight: 9,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/carian_thrusting_shield_thrusting_shields_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Carian Thrusting Shield",
        weapon_type: WeaponType.ThrustingShield,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 55,
        weight: 10.5,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nanayas_torch_1_torches_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Nanaya's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 51,
        weight: 3.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.AbyssalWoods],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/lamenting_visage_torch_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Lamenting Visage",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str],
        guard_boost: 48,
        weight: 2,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CharosHiddenGrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 1.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.Limgrave, Location.RoundtableHold],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/beast-repellent_torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "Beast-Repellent Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.Dragonbarrow],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/steel-wire_torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "Steel-Wire Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/sentrys_torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "Sentry's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 22,
        weight: 5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.CapitalOutskirts],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ghostflame_torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "Ghostflame Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.SiofraRiver],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/st_trinas_torch_weapon_elden_ring_wiki_guide_200px.png',
        name: "St Trina's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 20,
        weight: 3,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ConsectratedSnowfield],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dryleaf_seal_unique_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_75px.png',
        name: "Dryleaf Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fire_knights_seal_unique_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Fire Knight's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/spiraltree_seal_unique_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Spiraltree Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/finger_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Finger Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.Buy],
        location: [Location.RoundtableHold],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Erdtree Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/golden_order_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Golden Order Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CapitalOutskirts],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/gravel_stone_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Gravel Stone Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.GuaranteedDrop],
        location: [Location.Leyndell],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/giants_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Giant's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MountaintopsOfTheGiants],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godslayers_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Godslayer's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StoneswordKey],
        location: [Location.Limgrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/clawmark_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Clawmark Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward],
        location: [Location.Caelid],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/frenzied_flame_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Frenzied Flame Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward],
        location: [Location.Leyndell],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragon_communion_seal_sacred_seal_weapon_elden_ring_wiki_guide_200px.png',
        name: "Dragon Communion Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Fai, Stat.Arc],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StoneswordKey, WayToOptain.GuaranteedDrop],
        location: [Location.Limgrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/staff_of_the_great_beyond_glintstone_staff_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Staff of the Great Beyond",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Remembrance],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dryleaf_seal_glinstone_staff_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_75px.png',
        name: "Maternal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Arc],
        guard_boost: 13,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/astrologers_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Astrologer's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.Buy],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/glintstone_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.RandomDrop, WayToOptain.GuaranteedDrop],
        location: [Location.LiurniaOfTheLakes, Location.Limgrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/academy_glintstone_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Academy Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward, WayToOptain.RandomDrop],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/diggers_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Digger's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Caelid, Location.LiurniaOfTheLakes, Location.AltusPlateau],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/demi-human_queens_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Demi-Human Queen's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/azurs_glintstone_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Azur's Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 4,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/lusats_glintstone_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Lusat's Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 4,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.Caelid],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/carian_glintstone_staff_glintstone_staffs-elden-ring-wiki-guide-200.png',
        name: "Carian Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/carian_glintblade_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Carian Glintblade Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/carian_regal_scepter_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Carian Regal Scepter",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.Magic,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Remembrance],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/albinauric_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Albanauric Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Arc],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/staff_of_loss_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Staff of  Loss",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Caelid],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/gelmir_glintstone_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Gelmir Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crystal_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Crystal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rotten_crystal_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Rotten Crystal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MiquellasHailigtree],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/meteorite_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Meteorite Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Caelid],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/staff_of_the_guilty_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Staff of the Guilty",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MountaintopsOfTheGiants, Location.LiurniaOfTheLakes, Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/prince_of_deaths_staff_glintstonestaff_weapon_elden_ring_wiki_guide_200px.png',
        name: "Prince of Death's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.DeeprootDepths],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rabbaths_cannon_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Rabbath's Cannon",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 15,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/hand_ballista_ballista_weapon_elden_ring_wiki_guide_200px.png',
        name: "Hand Ballista",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 10,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/jar_cannon_ballista_weapon_elden_ring_wiki_guide_200px.png',
        name: "Jar Cannon",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 15,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Bossdrop],
        location: [Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/repeating_crossbow_crossbow_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Repeating Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 6,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/spread_crossbow_crossbow_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Spread Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/soldiers_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Soldier's Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 3.5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Limgrave, Location.LiurniaOfTheLakes, Location.Caelid, Location.AltusPlateau, Location.Leyndell, Location.MtGelmir, Location.ConsectratedSnowfield, Location.MiquellasHailigtree, Location.GravesitePlain, Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/light_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Light Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Buy],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/heavy_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Heavy Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5.5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Limgrave, Location.LiurniaOfTheLakes, Location.Caelid, Location.WeepingPeninsula, Location.ConsectratedSnowfield, Location.DeeprootDepths, Location.Leyndell, Location.MiquellasHailigtree, Location.ScaduAltus, Location.RauhBase, Location.GravesitePlain, Location.AncientRuinsOfRauh, Location.CeruleanCoast, Location.CharosHiddenGrave, Location.AbyssalWoods],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/arbalest_weapon_elden_ring_wiki_guide_200px.png',
        name: "Arbalest",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 6,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Limgrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crepuss_black-key_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Crepus's Black-Key Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.StoneswordKey],
        location: [Location.RoundtableHold],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/pulley_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Pulley Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/full_moon_crossbow_weapon_elden_ring_wiki_guide_200px.png',
        name: "Full Moon Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
]
