
import GreatKatanaIcon from '../../../icons/eldenringitems/GreatKatana.png'
import DragonHuntersGreatKatanaIcon from '../../../icons/eldenringitems/DragonHuntersGreatKatana.png'
import RakshasasGreatKatanaIcon from '../../../icons/eldenringitems/RakshasasGreatKatana.png'
import MiladyIcon from '../../../icons/eldenringitems/Milady.png'
import LedasSwordIcon from '../../../icons/eldenringitems/LedasSword.png'
import RellanasTwinBladesIcon from '../../../icons/eldenringitems/RellanasTwinBlades.png'
import RedBearsClawIcon from '../../../icons/eldenringitems/RedBearsClaw.png'
import BeastClawIcon from '../../../icons/eldenringitems/BeastClaw.png'
import FiresparkPerfumeBottleIcon from '../../../icons/eldenringitems/FiresparkPerfumeBottle.png'
import ChillingPerfumeBottleIcon from '../../../icons/eldenringitems/ChillingPerfumeBottle.png'
import FrenzyflamePerfumeBottleIcon from '../../../icons/eldenringitems/FrenzyflamePerfumeBottle.png'
import LightningPerfumeBottleIcon from '../../../icons/eldenringitems/LightningPerfumeBottle.png'
import DeadlyPoisonPerfumeBottleIcon from '../../../icons/eldenringitems/DeadlyPoisonPerfumeBottle.png'
import BackhandBladeIcon from '../../../icons/eldenringitems/BackhandBlade.png'
import SmithscriptCirqueIcon from '../../../icons/eldenringitems/SmithscriptCirque.png'
import CursebladesCirqueIcon from '../../../icons/eldenringitems/CursebladesCirque.png'
import SmithscriptDaggerIcon from '../../../icons/eldenringitems/SmithscriptDagger.png'
import DryleafArtsIcon from '../../../icons/eldenringitems/DryleafArts.png'
import DanesFootworkIcon from '../../../icons/eldenringitems/DanesFootwork.png'
import DuelingShieldIcon from '../../../icons/eldenringitems/DuelingShield.png'
import CarianThrustingShieldIcon from '../../../icons/eldenringitems/CarianThrustingShield.png'
import NanayasTorchIcon from '../../../icons/eldenringitems/NanayasTorch.png'
import LamentingVisageIcon from '../../../icons/eldenringitems/LamentingVisage.png'
import TorchIcon from '../../../icons/eldenringitems/Torch.png'
import BeastRepellentTorchIcon from '../../../icons/eldenringitems/BeastRepellentTorch.png'
import SteelWireTorchIcon from '../../../icons/eldenringitems/SteelWireTorch.png'
import SentrysTorchIcon from '../../../icons/eldenringitems/SentrysTorch.png'
import GhostflameTorchIcon from '../../../icons/eldenringitems/GhostflameTorch.png'
import StTrinasTorchIcon from '../../../icons/eldenringitems/StTrinasTorch.png'
import DryleafSealIcon from '../../../icons/eldenringitems/DryleafSeal.png'
import FireKnightsSealIcon from '../../../icons/eldenringitems/FireKnightsSeal.png'
import SpiraltreeSealIcon from '../../../icons/eldenringitems/SpiraltreeSeal.png'
import FingerSealIcon from '../../../icons/eldenringitems/FingerSeal.png'
import ErdtreeSealIcon from '../../../icons/eldenringitems/ErdtreeSeal.png'
import GoldenOrderSealIcon from '../../../icons/eldenringitems/GoldenOrderSeal.png'
import GravelStoneSealIcon from '../../../icons/eldenringitems/GravelStoneSeal.png'
import GiantsSealIcon from '../../../icons/eldenringitems/GiantsSeal.png'
import GodslayersSealIcon from '../../../icons/eldenringitems/GodslayersSeal.png'
import ClawmarkSealIcon from '../../../icons/eldenringitems/ClawmarkSeal.png'
import FrenziedFlameSealIcon from '../../../icons/eldenringitems/FrenziedFlameSeal.png'
import DragonCommunionSealIcon from '../../../icons/eldenringitems/DragonCommunionSeal.png'
import StaffOfTheGreatBeyondIcon from '../../../icons/eldenringitems/StaffOfTheGreatBeyond.png'
import MaternalStaffIcon from '../../../icons/eldenringitems/MaternalStaff.png'
import AstrologersStaffIcon from '../../../icons/eldenringitems/AstrologersStaff.png'
import GlintstoneStaffIcon from '../../../icons/eldenringitems/GlintstoneStaff.png'
import AcademyGlintstoneStaffIcon from '../../../icons/eldenringitems/AcademyGlintstoneStaff.png'
import DiggersStaffIcon from '../../../icons/eldenringitems/DiggersStaff.png'
import DemiHumanQueensStaffIcon from '../../../icons/eldenringitems/DemiHumanQueensStaff.png'
import AzursGlintstoneStaffIcon from '../../../icons/eldenringitems/AzursGlintstoneStaff.png'
import LusatsGlintstoneStaffIcon from '../../../icons/eldenringitems/LusatsGlintstoneStaff.png'
import CarianGlintstoneStaffIcon from '../../../icons/eldenringitems/CarianGlintstoneStaff.png'
import CarianGlintbladeStaffIcon from '../../../icons/eldenringitems/CarianGlintbladeStaff.png'
import CarianRegalScepterIcon from '../../../icons/eldenringitems/CarianRegalScepter.png'
import AlbinauricStaffIcon from '../../../icons/eldenringitems/AlbinauricStaff.png'
import StaffOfLossIcon from '../../../icons/eldenringitems/StaffOfLoss.png'
import GelmirGlintstoneStaffIcon from '../../../icons/eldenringitems/GelmirGlintstoneStaff.png'
import CrystalStaffIcon from '../../../icons/eldenringitems/CrystalStaff.png'
import RottenCrystalStaffIcon from '../../../icons/eldenringitems/RottenCrystalStaff.png'
import MeteoriteStaffIcon from '../../../icons/eldenringitems/MeteoriteStaff.png'
import StaffOfTheGuiltyIcon from '../../../icons/eldenringitems/StaffOfTheGuilty.png'
import PrinceOfDeathsStaffIcon from '../../../icons/eldenringitems/PrinceOfDeathsStaff.png'
import RabbathsCannonIcon from '../../../icons/eldenringitems/RabbathsCannon.png'
import HandBallistaIcon from '../../../icons/eldenringitems/HandBallista.png'
import JarCannonIcon from '../../../icons/eldenringitems/JarCannon.png'
import RepeatingCrossbowIcon from '../../../icons/eldenringitems/RepeatingCrossbow.png'
import SpreadCrossbowIcon from '../../../icons/eldenringitems/SpreadCrossbow.png'
import SoldiersCrossbowIcon from '../../../icons/eldenringitems/SoldiersCrossbow.png'
import LightCrossbowIcon from '../../../icons/eldenringitems/LightCrossbow.png'
import HeavyCrossbowIcon from '../../../icons/eldenringitems/HeavyCrossbow.png'
import ArbalestIcon from '../../../icons/eldenringitems/Arbalest.png'
import CrepussBlackKeyCrossbowIcon from '../../../icons/eldenringitems/CrepussBlackKeyCrossbow.png'
import PulleyCrossbowIcon from '../../../icons/eldenringitems/PulleyCrossbow.png'
import FullMoonCrossbowIcon from '../../../icons/eldenringitems/FullMoonCrossbow.png'
import IgonsGreatbowIcon from '../../../icons/eldenringitems/IgonsGreatbow.png'
import GreatbowIcon from '../../../icons/eldenringitems/Greatbow.png'
import GolemGreatbowIcon from '../../../icons/eldenringitems/GolemGreatbow.png'
import ErdtreeGreatbowIcon from '../../../icons/eldenringitems/ErdtreeGreatbow.png'
import LionGreatbowIcon from '../../../icons/eldenringitems/LionGreatbow.png'
import AnsbachsLongbowIcon from '../../../icons/eldenringitems/AnsbachsLongbow.png'

export type ERItem = {
    icon: string
    name: string
    weapon_type: WeaponType
    scaling: Stat[]
    ash_of_war: AshOfWar
    guard_boost: number
    damage: DamageType[]
    weight: number
    optain: WayToOptain[]
    location: Location[]
    id: number
}

enum WayToOptain {
    Remembrance = 'Remembrance',
    Bossdrop = 'Boss Reward',
    FindInWorld = 'Find in World',
    Buy = 'Buy',
    GuaranteedDrop = 'Guaranteed Drop',
    RandomDrop = 'Random Drop',
    StartingEquipment = 'Starting Equipment',
    StoneswordKey = 'Stonesword Key',
    QuestReward = 'Quest Reward',
}

enum WeaponType {
    Dagger = 'Dagger',
    StraightSword = 'Straight Sword',
    Greatsword = 'Greatsword',
    ColossalSword = 'Colossal Sword',
    ThrustingSword = 'Thrusting Sword',
    HeavyThrustingSword = 'Heavy Thrusting Sword',
    CurvedSword = 'Curved Sword',
    CurvedGreatsword = 'Curved Greatsword',
    Katana = 'Katana',
    Twinblade = 'Twinblade',
    Axe = 'Axe',
    Greataxe = 'Greataxe',
    Hammer = 'Hammer',
    Flail = 'Flail',
    GreatHammer = 'Great Hammer',
    ColossalWeapon = 'Colossal Weapon',
    Spear = 'Spear',
    GreatSpear = 'Great Spear',
    Halberd = 'Halberd',
    Reaper = 'Reaper',
    Whip = 'Whip',
    Fist = 'Fist',
    Claw = 'Claw',
    LightBow = 'Light Bow',
    Bow = 'Bow',
    Greatbow = 'Greatbow',
    Crossbow = 'Crossbow',
    Ballista = 'Ballista',
    GlintstoneStaff = 'Glintstone Staff',
    SacredSeal = 'Sacred Seal',
    Torch = 'Torch',
    ThrustingShield = 'Thrusting Shield',
    HandToHandArt = 'Hand-to-Hand Art',
    ThrowingBlade = 'Throwing Blade',
    BackhandBlade = 'Backhand Blade',
    PerfumeBottle = 'Perfume Bottle',
    BeastClaw = 'Beast Claw',
    LightGreatsword = 'Light Greatsword',
    GreatKatana = 'Great Katana',
    SmallShield = 'Small Shield',
    MediumShield = 'Medium Shield',
    Greatshield = 'Greatshield',
}

enum Location {
    AinselRiver = 'Ainsel River',
    DeeprootDepths = 'Deeproot Depths',
    SiofraRiver = 'Siofra River',

    Limgrave = 'Limgrave',
    WeepingPeninsula = 'Weeping Peninsula',
    LiurniaOfTheLakes = 'Liurnia of the Lakes',
    Caelid = 'Caelid',
    Dragonbarrow = 'Dragonbarrow',
    AltusPlateau = 'Altus Plateau',
    MtGelmir = 'Mt. Gelmir',
    CapitalOutskirts = 'Capital Outskirts',
    Leyndell = 'Leyndell',
    MountaintopsOfTheGiants = 'Mountaintops of the Giants',
    CrumblingFaramAzula = 'Crumbling Faram Azula',
    ForbiddenLands = 'Forbidden Lands',
    ConsectratedSnowfield = 'Consectrated Snowfield',
    MiquellasHailigtree = 'Miquella\'s Hailigtree',

    GravesitePlain = 'Gravesite Plain',
    ScaduAltus = 'Scadu Altus',
    RauhBase = 'Rauh Base',
    AncientRuinsOfRauh = 'Ancient Ruins of Rauh',
    CeruleanCoast = 'Cerulean Coast',
    CharosHiddenGrave = 'Charo\'s Hidden Grave',
    JaggedPeak = 'Jagged Peak',
    AbyssalWoods = 'Abyssal Woods',
    FingerRuinsOfRhia = 'Finger Ruins of Rhia',
    ScaduView = 'Scadu View',
    EnirIlim = 'Enir Ilim',
    Hinterlands = 'Hinterlands',

    RoundtableHold = 'Roundtable Hold',
}

enum Stat {
    Str = 'Str',
    Dex = 'Dex',
    Int = 'Int',
    Fai = 'Fai',
    Arc = 'Arc',
}

enum AshOfWar {
    Standard = 'Standard',
    Heavy = 'Heavy',
    Keen = 'Keen',
    Quality = 'Quality',
    Fire = 'Fire',
    FlameArt = 'Flame Art',
    Lightning = 'Lightning',
    Sacred = 'Sacred',
    Magic = 'Magic',
    Cold = 'Cold',
    Poison = 'Poison',
    Blood = 'Blood',
    Occult = 'Occult',

    Unique = 'Unique',
    NoSkill = 'No Skill',
}

enum DamageType {
    Standard = 'Standard',
    Strike = 'Strike',
    Slash = 'Slash',
    Pierce = 'Pierce',
}

const allEldenRingItemsNoId: any[] = [
    {
        icon: GreatKatanaIcon,
        name: "Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: DragonHuntersGreatKatanaIcon,
        name: "Dragon-Hunter's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 37,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 10.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: RakshasasGreatKatanaIcon,
        name: "Rakshasa's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: MiladyIcon,
        name: "Milady",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 36,
        damage: [DamageType.Standard, DamageType.Pierce],
        weight: 6.5,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: LedasSwordIcon,
        name: "Leda's Sword",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 35,
        weight: 7.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Bossdrop],
        location: [Location.EnirIlim],
    },
    {
        icon: RellanasTwinBladesIcon,
        name: "Rellana's Twin Blades",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 35,
        weight: 8,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Remembrance],
        location: [Location.GravesitePlain],
    },
    {
        icon: RedBearsClawIcon,
        name: "Red Bear's Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 22,
        weight: 4,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: BeastClawIcon,
        name: "Beast Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 3,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: FiresparkPerfumeBottleIcon,
        name: "Firespark Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: ChillingPerfumeBottleIcon,
        name: "Chilling Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Int],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CharosHiddenGrave],
    },
    {
        icon: FrenzyflamePerfumeBottleIcon,
        name: "Frenzyflame Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.AbyssalWoods],
    },
    {
        icon: LightningPerfumeBottleIcon,
        name: "Lightning Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CeruleanCoast],
    },
    {
        icon: DeadlyPoisonPerfumeBottleIcon,
        name: "Deadly Poison Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Arc],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard],
        optain: [WayToOptain.Buy],
        location: [Location.GravesitePlain],
    },
    {
        icon: BackhandBladeIcon,
        name: "Backhand Blade",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 15,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: SmithscriptCirqueIcon,
        name: "Smithscript Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 25,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: CursebladesCirqueIcon,
        name: "Curseblade's Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 45,
        weight: 4.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.RandomDrop],
        location: [Location.GravesitePlain, Location.EnirIlim, Location.ScaduAltus, Location.AbyssalWoods, Location.CharosHiddenGrave, Location.CeruleanCoast, Location.AncientRuinsOfRauh],
    },
    {
        icon: SmithscriptDaggerIcon,
        name: "Smithscript Dagger",
        weapon_type: WeaponType.ThrowingBlade,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: DryleafArtsIcon,
        name: "Dryleaf Arts",
        weapon_type: WeaponType.HandToHandArt,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 1,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: DanesFootworkIcon,
        name: "Dane's Footwork",
        weapon_type: WeaponType.HandToHandArt,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 1,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.EnirIlim],
    },
    {
        icon: DuelingShieldIcon,
        name: "Dueling Shield",
        weapon_type: WeaponType.ThrustingShield,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 50,
        weight: 9,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: CarianThrustingShieldIcon,
        name: "Carian Thrusting Shield",
        weapon_type: WeaponType.ThrustingShield,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 55,
        weight: 10.5,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: NanayasTorchIcon,
        name: "Nanaya's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 51,
        weight: 3.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.AbyssalWoods],
    },
    {
        icon: LamentingVisageIcon,
        name: "Lamenting Visage",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str],
        guard_boost: 48,
        weight: 2,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CharosHiddenGrave],
    },
    {
        icon: TorchIcon,
        name: "Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 1.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.Limgrave, Location.RoundtableHold],
    },
    {
        icon: BeastRepellentTorchIcon,
        name: "Beast-Repellent Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.Dragonbarrow],
    },
    {
        icon: SteelWireTorchIcon,
        name: "Steel-Wire Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: SentrysTorchIcon,
        name: "Sentry's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 22,
        weight: 5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Buy],
        location: [Location.CapitalOutskirts],
    },
    {
        icon: GhostflameTorchIcon,
        name: "Ghostflame Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 19,
        weight: 2.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.SiofraRiver],
    },
    {
        icon: StTrinasTorchIcon,
        name: "St Trina's Torch",
        weapon_type: WeaponType.Torch,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 20,
        weight: 3,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ConsectratedSnowfield],
    },
    {
        icon: DryleafSealIcon,
        name: "Dryleaf Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: FireKnightsSealIcon,
        name: "Fire Knight's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: SpiraltreeSealIcon,
        name: "Spiraltree Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: FingerSealIcon,
        name: "Finger Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.Buy],
        location: [Location.RoundtableHold],
    },
    {
        icon: ErdtreeSealIcon,
        name: "Erdtree Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: GoldenOrderSealIcon,
        name: "Golden Order Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CapitalOutskirts],
    },
    {
        icon: GravelStoneSealIcon,
        name: "Gravel Stone Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.GuaranteedDrop],
        location: [Location.Leyndell],
    },
    {
        icon: GiantsSealIcon,
        name: "Giant's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MountaintopsOfTheGiants],
    },
    {
        icon: GodslayersSealIcon,
        name: "Godslayer's Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StoneswordKey, WayToOptain.FindInWorld],
        location: [Location.Limgrave],
    },
    {
        icon: ClawmarkSealIcon,
        name: "Clawmark Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 15,
        weight: 1.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward],
        location: [Location.Caelid],
    },
    {
        icon: FrenziedFlameSealIcon,
        name: "Frenzied Flame Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward],
        location: [Location.Leyndell],
    },
    {
        icon: DragonCommunionSealIcon,
        name: "Dragon Communion Seal",
        weapon_type: WeaponType.SacredSeal,
        scaling: [Stat.Fai, Stat.Arc],
        guard_boost: 15,
        weight: 0,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StoneswordKey, WayToOptain.GuaranteedDrop],
        location: [Location.Limgrave],
    },
    {
        icon: StaffOfTheGreatBeyondIcon,
        name: "Staff of the Great Beyond",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Remembrance],
        location: [Location.ScaduAltus],
    },
    {
        icon: MaternalStaffIcon,
        name: "Maternal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Arc],
        guard_boost: 13,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: AstrologersStaffIcon,
        name: "Astrologer's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.Buy],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: GlintstoneStaffIcon,
        name: "Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.StartingEquipment, WayToOptain.RandomDrop, WayToOptain.GuaranteedDrop],
        location: [Location.LiurniaOfTheLakes, Location.Limgrave],
    },
    {
        icon: AcademyGlintstoneStaffIcon,
        name: "Academy Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.QuestReward, WayToOptain.RandomDrop],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: DiggersStaffIcon,
        name: "Digger's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Caelid, Location.LiurniaOfTheLakes, Location.AltusPlateau],
    },
    {
        icon: DemiHumanQueensStaffIcon,
        name: "Demi-Human Queen's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: AzursGlintstoneStaffIcon,
        name: "Azur's Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 4,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: LusatsGlintstoneStaffIcon,
        name: "Lusat's Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 4,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Bossdrop],
        location: [Location.Caelid],
    },
    {
        icon: CarianGlintstoneStaffIcon,
        name: "Carian Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: CarianGlintbladeStaffIcon,
        name: "Carian Glintblade Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: CarianRegalScepterIcon,
        name: "Carian Regal Scepter",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.Magic,
        damage: [DamageType.Strike],
        optain: [WayToOptain.Remembrance],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: AlbinauricStaffIcon,
        name: "Albinauric Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Arc],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: StaffOfLossIcon,
        name: "Staff of Loss",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Dex, Stat.Int],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Caelid],
    },
    {
        icon: GelmirGlintstoneStaffIcon,
        name: "Gelmir Glintstone Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 14,
        weight: 2.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MtGelmir],
    },
    {
        icon: CrystalStaffIcon,
        name: "Crystal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: RottenCrystalStaffIcon,
        name: "Rotten Crystal Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MiquellasHailigtree],
    },
    {
        icon: MeteoriteStaffIcon,
        name: "Meteorite Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Caelid],
    },
    {
        icon: StaffOfTheGuiltyIcon,
        name: "Staff of the Guilty",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Fai],
        guard_boost: 17,
        weight: 4.5,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.RandomDrop],
        location: [Location.MountaintopsOfTheGiants, Location.LiurniaOfTheLakes, Location.MtGelmir],
    },
    {
        icon: PrinceOfDeathsStaffIcon,
        name: "Prince of Death's Staff",
        weapon_type: WeaponType.GlintstoneStaff,
        scaling: [Stat.Str, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 3,
        ash_of_war: AshOfWar.NoSkill,
        damage: [DamageType.Strike],
        optain: [WayToOptain.FindInWorld],
        location: [Location.DeeprootDepths],
    },
    {
        icon: RabbathsCannonIcon,
        name: "Rabbath's Cannon",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 15,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: HandBallistaIcon,
        name: "Hand Ballista",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 10,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: JarCannonIcon,
        name: "Jar Cannon",
        weapon_type: WeaponType.Ballista,
        scaling: [],
        guard_boost: 0,
        weight: 15,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Bossdrop],
        location: [Location.MtGelmir],
    },
    {
        icon: RepeatingCrossbowIcon,
        name: "Repeating Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 6,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: SpreadCrossbowIcon,
        name: "Spread Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: SoldiersCrossbowIcon,
        name: "Soldier's Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 3.5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Limgrave, Location.LiurniaOfTheLakes, Location.Caelid, Location.AltusPlateau, Location.Leyndell, Location.MtGelmir, Location.ConsectratedSnowfield, Location.MiquellasHailigtree, Location.GravesitePlain, Location.ScaduAltus],
    },
    {
        icon: LightCrossbowIcon,
        name: "Light Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Buy],
        location: [Location.WeepingPeninsula],
    },
    {
        icon: HeavyCrossbowIcon,
        name: "Heavy Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5.5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Limgrave, Location.LiurniaOfTheLakes, Location.Caelid, Location.WeepingPeninsula, Location.ConsectratedSnowfield, Location.DeeprootDepths, Location.Leyndell, Location.MiquellasHailigtree, Location.ScaduAltus, Location.RauhBase, Location.GravesitePlain, Location.AncientRuinsOfRauh, Location.CeruleanCoast, Location.CharosHiddenGrave, Location.AbyssalWoods],
    },
    {
        icon: ArbalestIcon,
        name: "Arbalest",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 6,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.Limgrave],
    },
    {
        icon: CrepussBlackKeyCrossbowIcon,
        name: "Crepus's Black-Key Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 5,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.StoneswordKey, WayToOptain.FindInWorld],
        location: [Location.RoundtableHold],
    },
    {
        icon: PulleyCrossbowIcon,
        name: "Pulley Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.MtGelmir],
    },
    {
        icon: FullMoonCrossbowIcon,
        name: "Full Moon Crossbow",
        weapon_type: WeaponType.Crossbow,
        scaling: [],
        guard_boost: 0,
        weight: 4,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.LiurniaOfTheLakes],
    },
    {
        icon: IgonsGreatbowIcon,
        name: "Igon's Greatbow",
        weapon_type: WeaponType.Greatbow,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 0,
        weight: 12.5,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.GuaranteedDrop, WayToOptain.QuestReward],
        location: [Location.GravesitePlain, Location.JaggedPeak],
    },
    {
        icon: GreatbowIcon,
        name: "Greatbow",
        weapon_type: WeaponType.Greatbow,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 0,
        weight: 10,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.FindInWorld, WayToOptain.RandomDrop],
        location: [Location.AltusPlateau, Location.Caelid, Location.Leyndell, Location.ScaduAltus, Location.GravesitePlain, Location.RauhBase, Location.AbyssalWoods, Location.ConsectratedSnowfield, Location.DeeprootDepths],
    },
    {
        icon: GolemGreatbowIcon,
        name: "Golem Greatbow",
        weapon_type: WeaponType.Greatbow,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 0,
        weight: 14.5,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.RandomDrop],
        location: [Location.Limgrave, Location.Caelid, Location.AltusPlateau, Location.WeepingPeninsula, Location.MountaintopsOfTheGiants],
    },
    {
        icon: ErdtreeGreatbowIcon,
        name: "Erdtree Greatbow",
        weapon_type: WeaponType.Greatbow,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 0,
        weight: 11,
        ash_of_war: AshOfWar.Standard,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.StoneswordKey, WayToOptain.GuaranteedDrop],
        location: [Location.Limgrave],
    },
    {
        icon: LionGreatbowIcon,
        name: "Lion Greatbow",
        weapon_type: WeaponType.Greatbow,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 0,
        weight: 9.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Remembrance],
        location: [Location.Caelid],
    },
    {
        icon: AnsbachsLongbowIcon,
        name: "Ansbach's Longbow",
        weapon_type: WeaponType.Bow,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 0,
        weight: 4.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Pierce],
        optain: [WayToOptain.Bossdrop, WayToOptain.QuestReward],
        location: [Location.EnirIlim],
    },
]

export const allEldenRingItems: ERItem[] = allEldenRingItemsNoId.map((item, index) => {return {...item, id: index}})
