
export type ERItem = {
    icon: string
    name: string
    weapon_type: WeaponType
    scaling: Stat[]
    ash_of_war: AshOfWar
    guard_boost: number
    damage: DamageType[]
    weight: number
    optain: WayToOptain[]
    location: Location[]
}

export type RatedERItem = ERItem & {
    c_scaling: ParticalCorrectList,
    c_damage: ParticalCorrectList,
    c_optain: ParticalCorrectList,
    c_location: ParticalCorrectList,
}

export type ParticalCorrectList = 'y' | 'n' | 'p'

enum WayToOptain {
    Remembrance = 'Remembrance',
    Bossdrop = 'Bossdrop',
    FindInWorld = 'Find in World',
    Buy = 'Buy',
    RandomDrop = 'Random Drop',
}

enum WeaponType {
    Dagger = 'Dagger',
    StraightSword = 'Straight Sword',
    Greatsword = 'Greatsword',
    ColossalSword = 'Colossal Sword',
    ThrustingSword = 'Thrusting Sword',
    HeavyThrustingSword = 'Heavy Thrusting Sword',
    CurvedSword = 'Curved Sword',
    CurvedGreatsword = 'Curved Greatsword',
    Katana = 'Katana',
    Twinblade = 'Twinblade',
    Axe = 'Axe',
    Greataxe = 'Greataxe',
    Hammer = 'Hammer',
    Flail = 'Flail',
    GreatHammer = 'Great Hammer',
    ColossalWeapon = 'Colossal Weapon',
    Spear = 'Spear',
    GreatSpear = 'Great Spear',
    Halberd = 'Halberd',
    Reaper = 'Reaper',
    Whip = 'Whip',
    Fist = 'Fist',
    Claw = 'Claw',
    LightBow = 'Light Bow',
    Bow = 'Bow',
    Greatbow = 'Greatbow',
    Crossbow = 'Crossbow',
    Ballista = 'Ballista',
    GlintstoneStaff = 'Glintstone Staff',
    SacredSeal = 'Sacred Seal',
    Torch = 'Torch',
    Tool = 'Tool',
    ThrustingShield = 'Thrusting Shield',
    HandToHandArt = 'Hand-to-Hand Art',
    ThrowingBlade = 'Throwing Blade',
    BackhandBlade = 'Backhand Blade',
    PerfumeBottle = 'Perfume Bottle',
    BeastClaw = 'Beast Claw',
    LightGreatsword = 'Light Greatsword',
    GreatKatana = 'Great Katana',
    SmallShield = 'Small Shield',
    MediumShield = 'Medium Shield',
    Greatshield = 'Greatshield',
}

enum Location {
    AinselRiver = 'Ainsel River',
    DeeprootDepths = 'Deeproot Depths',
    SiofraRiver = 'Siofra River',

    Limgrave = 'Limgrave',
    WeepingPeninsula = 'Weeping Peninsula',
    LiurniaOfTheLakes = 'Liurnia of the Lakes',
    Caelid = 'Caelid',
    Dragonbarrow = 'Dragonbarrow',
    AltusPlateau = 'Altus Plateau',
    MtGelmir = 'Mt. Gelmir',
    CapitalOutskirts = 'Capital Outskirts',
    Leyndell = 'Leyndell',
    MountaintopsOfTheGiants = 'Mountaintops of the Giants',
    CrumblingFaramAzula = 'Crumbling Faram Azula',
    ForbiddenLands = 'Forbidden Lands',
    ConsectratedSnowfield = 'Consectrated Snowfield',
    MiquellasHailigtree = 'Miquella\'s Hailigtree',

    GravesitePlain = 'Gravesite Plain',
    ScaduAltus = 'Scadu Altus',
    RauhBase = 'Rauh Base',
    AncientRuinsOfRauh = 'Ancient Ruins of Rauh',
    CeruleanCoast = 'Cerulean Coast',
    CharosHiddenGrave = 'Charo\'s Hidden Grave',
    JaggedPeak = 'Jagged Peak',
    AbyssalWoods = 'Abyssal Woods',
    FingerRuinsOfRhia = 'Finger Ruins of Rhia',
    ScaduView = 'Scadu View',
    EnirIlim = 'Enir Ilim',
}

enum Stat {
    Str = 'Str',
    Dex = 'Dex',
    Int = 'Int',
    Fai = 'Fai',
    Arc = 'Arc',
}

enum AshOfWar {
    Standard = 'Standard',
    Heavy = 'Heavy',
    Keen = 'Keen',
    Quality = 'Quality',
    Fire = 'Fire',
    FlameArt = 'Flame Art',
    Lightning = 'Lightning',
    Sacred = 'Sacred',
    Magic = 'Magic',
    Cold = 'Cold',
    Poison = 'Poison',
    Blood = 'Blood',
    Occult = 'Occult',

    Unique = 'Unique',
}

enum DamageType {
    Standard = 'Standard',
    Strike = 'Strike',
    Slash = 'Slash',
    Pierce = 'Pierce',
}

export const AllEldenRingItems: ERItem[] = [
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/great_katana_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragon-hunters_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Dragon-Hunter's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 37,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 10.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rakshasas_great_katana_great_katana_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Rakshasa's Great Katana",
        weapon_type: WeaponType.GreatKatana,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Unique,
        guard_boost: 35,
        damage: [DamageType.Slash, DamageType.Pierce],
        weight: 9.5,
        optain: [WayToOptain.Bossdrop],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/milady_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Milady",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex],
        ash_of_war: AshOfWar.Keen,
        guard_boost: 36,
        damage: [DamageType.Standard, DamageType.Pierce],
        weight: 6.5,
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ledas_sword_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Leda's Sword",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Fai],
        guard_boost: 35,
        weight: 7.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Bossdrop],
        location: [Location.EnirIlim],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rellanas_twinblade_light_greatswords_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Rellana's Twin Blades",
        weapon_type: WeaponType.LightGreatsword,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 35,
        weight: 8,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard, DamageType.Pierce],
        optain: [WayToOptain.Remembrance],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/red_bears_claw_beast_claws_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Red Bear's Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 22,
        weight: 4,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/beast_claw_beast_claws_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Beast Claw",
        weapon_type: WeaponType.BeastClaw,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 20,
        weight: 3,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.Bossdrop],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/firespark_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Firespark Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/chilling_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Chilling Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Int],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CharosHiddenGrave],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/frenzyflame_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Frenzyflame Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.AbyssalWoods],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/lightning_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Lightning Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Fai],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Heavy,
        damage: [DamageType.Standard],
        optain: [WayToOptain.FindInWorld],
        location: [Location.CeruleanCoast],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/deadly_poison_perfume_bottle_perfume_bottles_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Deadly Poison Perfume Bottle",
        weapon_type: WeaponType.PerfumeBottle,
        scaling: [Stat.Dex, Stat.Arc],
        guard_boost: 15,
        weight: 1,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Standard],
        optain: [WayToOptain.Buy],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/backhand_blade_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Backhand Blade",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 15,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash, DamageType.Pierce],
        optain: [WayToOptain.FindInWorld],
        location: [Location.GravesitePlain],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/smithscript_cirque_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Smithscript Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex, Stat.Int, Stat.Fai],
        guard_boost: 25,
        weight: 2,
        ash_of_war: AshOfWar.Keen,
        damage: [DamageType.Slash],
        optain: [WayToOptain.FindInWorld],
        location: [Location.ScaduAltus],
    },
    {
        icon: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/curseblades_cirque_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png',
        name: "Curseblade's Cirque",
        weapon_type: WeaponType.BackhandBlade,
        scaling: [Stat.Str, Stat.Dex],
        guard_boost: 45,
        weight: 4.5,
        ash_of_war: AshOfWar.Unique,
        damage: [DamageType.Slash],
        optain: [WayToOptain.RandomDrop],
        location: [Location.GravesitePlain, Location.EnirIlim, Location.ScaduAltus, Location.AbyssalWoods, Location.CharosHiddenGrave, Location.CeruleanCoast, Location.AncientRuinsOfRauh],
    },
]
